version: 2
jobs:
  secret-thing:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run:
          name: 'use secret'
          command: |
            env



          
workflows:
  version: 2
  main:
    jobs:
      - secret-thing
