version: 2
jobs:
  secret-thing:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run:
          name: 'use secret'
          command: |
            mkdir /tmp/sensitive-artifacts
            echo "$MY_SECRET" > /tmp/sensitive-artifacts/MY_SECRET
      - store_artifacts:
          path: /tmp/sensitive-artifacts

          
workflows:
  version: 2
  main:
    jobs:
      - secret-thing
